### ISSUE TITLE
Question about target data

### ISSUE THREAD

**Issue by zkamvar** [cdcepi/FluSight-forecast-hub#1108]
I noticed that the [data source and timeframe changed](https://github.com/cdcepi/FluSight-forecast-hub/commit/54506c5ab6d41b91a7ea72cb4c4f0a84615d5dcb#diff-5a6f588b5f162f98c04be24923b75c767446efd9234dc73a2c593dfa09389232R14-R15) so that there is no longer flu data before 2024-11-02. Are the data before this date from this source invalid?

**Comment by smathis14** [comment]
They are valid. We originally truncated to only include data submitted through the new source under the updated requirements so that we wouldn't cause issues with the target data for the previous season. The old data source was the raw data submitted from facilities and states, the new data source undergoes quality control measures so the data may not always align. We plan to use the old source and original target data for the 23/24 and past seasons, but the new source and new target data for the 24/25 and likely beyond. Once the new preliminary data are released on Wednesday, we will include a longer timeseries.
